# These are supported funding model platforms

github: [muhammadawaisshaikh]
patreon: muhammadawaisshaikh
tidelift: https://github.com/muhammadawaisshaikh/reactjs-boilerplate-compelete
custom: ["https://www.paypal.com/paypalme/mawaisshaikh", muhammadawaisshaikh.com]
