# These are supported funding model platforms

github: [muhammadawaisshaikh]
twitter: awaisshaikh_
linkedin: muhammadawaisshaikh
custom: ["https://www.paypal.com/paypalme/mawaisshaikh", muhammadawaisshaikh.com]
